### ISSUE TITLE
[expath-file-module] Dependency problems found

### ISSUE THREAD

**Issue by joewiz** [exquery/exquery#30]
When I followed the instructions at https://github.com/eXist-db/expath-file-module for building exquery/expath-file-module, I encounter an error (see below for console output containing error stacktrace). 

Is there any additional information I should supply to help identify the problem? 

Background: I'm trying to run https://github.com/adamretter/fots-basex/tree/exist in eXist-db, and the queries depend on the EXPath file module (see https://github.com/adamretter/fots-basex/blob/exist/fots-environment.xqm#L16). 

```bash
$ git clone https://github.com/exquery/exquery.git
$ cd exquery/expath-file-module
$ mvn -e install
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building EXPath File Module 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ expath-file-module ---
[INFO] 
[INFO] --- buildversion-plugin:1.0.3:set-properties (default) @ expath-file-module ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ expath-file-module ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/joe/workspace/expath-file-module/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ expath-file-module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ expath-file-module ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.5
[WARNING]  org.exist-db.xquery.extensions.expath:expath-file-module:1.0-SNAPSHOT requires scala version: 2.11.5
[WARNING]  org.scalaz:scalaz-core_2.11:7.1.1 requires scala version: 2.11.5
[WARNING]  org.scala-lang.modules:scala-parser-combinators_2.11:1.0.2 requires scala version: 2.11.1
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ expath-file-module ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/joe/workspace/expath-file-module/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ expath-file-module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (default) @ expath-file-module ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.5
[WARNING]  org.exist-db.xquery.extensions.expath:expath-file-module:1.0-SNAPSHOT requires scala version: 2.11.5
[WARNING]  org.scalaz:scalaz-core_2.11:7.1.1 requires scala version: 2.11.5
[WARNING]  org.scala-lang.modules:scala-parser-combinators_2.11:1.0.2 requires scala version: 2.11.1
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ expath-file-module ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ expath-file-module ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ expath-file-module ---
[INFO] 
[INFO] --- maven-shade-plugin:3.0.0:shade (default) @ expath-file-module ---
[INFO] Including org.scala-lang:scala-library:jar:2.11.5 in the shaded jar.
[INFO] Including org.scalaz:scalaz-core_2.11:jar:7.1.1 in the shaded jar.
[INFO] Including org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.2 in the shaded jar.
[INFO] Including org.scala-lang.modules:scala-xml_2.11:jar:1.0.2 in the shaded jar.
[INFO] Including org.scalaz.stream:scalaz-stream_2.11:jar:0.6a in the shaded jar.
[INFO] Including org.scalaz:scalaz-concurrent_2.11:jar:7.1.0 in the shaded jar.
[INFO] Including org.scalaz:scalaz-effect_2.11:jar:7.1.0 in the shaded jar.
[INFO] Including org.typelevel:scodec-bits_2.11:jar:1.0.4 in the shaded jar.
[INFO] Including org.scala-lang:scala-reflect:jar:2.11.0 in the shaded jar.
[INFO] Including org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT in the shaded jar.
[INFO] Including com.github.scala-incubator.io:scala-io-file_2.11:jar:0.4.3-1 in the shaded jar.
[INFO] Including com.github.scala-incubator.io:scala-io-core_2.11:jar:0.4.3-1 in the shaded jar.
[INFO] Including com.madgag:scala-arm_2.11:jar:1.3.3 in the shaded jar.
[INFO] Including org.scala-lang.plugins:scala-continuations-library_2.11:jar:1.0.1 in the shaded jar.
[INFO] Attaching shaded artifact.
[INFO] 
[INFO] --- kuberam-expath-plugin:0.4.9:make-xar (create-xar) @ expath-file-module ---
[INFO] descriptorsDirectoryPath: /Users/joe/workspace/expath-file-module/target/expath-descriptors-d24bbc33-b2e1-4c7e-8c7d-0060bb0df82c
mavenResourcesExecution: org.apache.maven.shared.filtering.MavenResourcesExecution@3bf1aba7
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to /Users/joe/workspace/expath-file-module/target/make-xar-tmp
[INFO] Resolved artifact: org.exist-db.xquery.extensions.expath:expath-file-module:jar:1.0-SNAPSHOT
[INFO] artifactFile: /Users/joe/workspace/expath-file-module/target/expath-file-module-1.0-SNAPSHOT.jar
[INFO] Resolved artifact: org.scala-lang:scala-library:jar:2.11.5
[INFO] artifactFile: /Users/joe/.m2/repository/org/scala-lang/scala-library/2.11.5/scala-library-2.11.5.jar
[INFO] Resolved artifact: org.scalaz:scalaz-core_2.11:jar:7.1.1
[INFO] artifactFile: /Users/joe/.m2/repository/org/scalaz/scalaz-core_2.11/7.1.1/scalaz-core_2.11-7.1.1.jar
[INFO] Resolved artifact: org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.2
[INFO] artifactFile: /Users/joe/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.2/scala-parser-combinators_2.11-1.0.2.jar
[INFO] Resolved artifact: org.scala-lang.modules:scala-xml_2.11:jar:1.0.2
[INFO] artifactFile: /Users/joe/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
[INFO] Resolved artifact: org.scalaz.stream:scalaz-stream_2.11:jar:0.6a
[INFO] artifactFile: /Users/joe/.m2/repository/org/scalaz/stream/scalaz-stream_2.11/0.6a/scalaz-stream_2.11-0.6a.jar
[INFO] Resolved artifact: org.scalaz:scalaz-concurrent_2.11:jar:7.1.0
[INFO] artifactFile: /Users/joe/.m2/repository/org/scalaz/scalaz-concurrent_2.11/7.1.0/scalaz-concurrent_2.11-7.1.0.jar
[INFO] Resolved artifact: org.scalaz:scalaz-effect_2.11:jar:7.1.0
[INFO] artifactFile: /Users/joe/.m2/repository/org/scalaz/scalaz-effect_2.11/7.1.0/scalaz-effect_2.11-7.1.0.jar
[INFO] Resolved artifact: org.typelevel:scodec-bits_2.11:jar:1.0.4
[INFO] artifactFile: /Users/joe/.m2/repository/org/typelevel/scodec-bits_2.11/1.0.4/scodec-bits_2.11-1.0.4.jar
[INFO] Resolved artifact: org.scala-lang:scala-reflect:jar:2.11.0
[INFO] artifactFile: /Users/joe/.m2/repository/org/scala-lang/scala-reflect/2.11.0/scala-reflect-2.11.0.jar
[INFO] Resolved artifact: org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT
[INFO] artifactFile: /Users/joe/.m2/repository/org/exquery/expath/expath-file-module/1.0-SNAPSHOT/expath-file-module-1.0-SNAPSHOT.jar
[INFO] Resolved artifact: com.github.scala-incubator.io:scala-io-file_2.11:jar:0.4.3-1
[INFO] artifactFile: /Users/joe/.m2/repository/com/github/scala-incubator/io/scala-io-file_2.11/0.4.3-1/scala-io-file_2.11-0.4.3-1.jar
[INFO] Resolved artifact: com.github.scala-incubator.io:scala-io-core_2.11:jar:0.4.3-1
[INFO] artifactFile: /Users/joe/.m2/repository/com/github/scala-incubator/io/scala-io-core_2.11/0.4.3-1/scala-io-core_2.11-0.4.3-1.jar
[INFO] Resolved artifact: com.madgag:scala-arm_2.11:jar:1.3.3
[INFO] artifactFile: /Users/joe/.m2/repository/com/madgag/scala-arm_2.11/1.3.3/scala-arm_2.11-1.3.3.jar
[INFO] Resolved artifact: org.scala-lang.plugins:scala-continuations-library_2.11:jar:1.0.1
[INFO] artifactFile: /Users/joe/.m2/repository/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.1/scala-continuations-library_2.11-1.0.1.jar
mavenResourcesExecution: org.apache.maven.shared.filtering.MavenResourcesExecution@5c486c5a
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to /Users/joe/workspace/expath-file-module/target/expath-descriptors-d24bbc33-b2e1-4c7e-8c7d-0060bb0df82c
[INFO] Building zip: /Users/joe/workspace/expath-file-module/target/expath-file-module-1.0-SNAPSHOT.xar
[INFO] 
[INFO] --- maven-dependency-plugin:3.0.1:analyze-only (analyze) @ expath-file-module ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.scalaz:scalaz-concurrent_2.11:jar:7.1.0:compile
[WARNING]    com.madgag:scala-arm_2.11:jar:1.3.3:compile
[WARNING]    org.typelevel:scodec-bits_2.11:jar:1.0.4:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.733 s
[INFO] Finished at: 2017-09-01T22:35:09-05:00
[INFO] Final Memory: 40M/517M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project expath-file-module: Dependency problems found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project expath-file-module: Dependency problems found
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency problems found
	at org.apache.maven.plugins.dependency.analyze.AbstractAnalyzeMojo.execute(AbstractAnalyzeMojo.java:261)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by adamretter** [comment]
@joewiz I think this should now be fixed. Can you test again, pulling in the latest source code?
